### PR TITLE
TRITON-1636 update triton-mockcloud base image to triton-origin-x86_64-18.4.0

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by cburroughs** [comment]
Build example:  https://jenkins.joyent.us/job/18.4-mockcloud/2/console

I'm not sure if there is any particular pre-merge testing procedure that would make sense for this component.

**Comment by trentm** [comment]
> I'm not sure if there is any particular pre-merge testing procedure that would make sense for this component.

@cburroughs Have you tried to use it? Using the `mockcloud-deploy` script mentioned here: https://github.com/joyent/triton-mockcloud#how-to-create-a-mockcloud-vm

**Comment by cburroughs** [comment]
I ran `./mockcloud-deploy -i 69b3a17d-0c8f-4ae4-a42b-4c439e3029e6 headnode 12` no nightly-4.

That resulted in
```
online         18:24:32 svc:/triton/mockcloud-setup:default
```
and `sdc-server list` returning a long list of "VC" hostnames, so I think that's a success.

**Comment by trentm** [comment]
ship it

**Pull request merged**
