### PR TITLE
TRITON-1943 add Jenkinsfiles to Triton repositories

### PR DESCRIPTION
**Pull request by cburroughs**

### CODE REVIEW

**Comment by trentm** [comment]
So this is an unfortunate one. This is failing in `make check` when attempting to run eslint. I can repro this same thing on my Mac.

eslint cannot run because not all of the modules it is configured to use are installed after `make distclean check`. This repo's .eslintrc file has:

```
    "plugins": [
        "joyent",
        "prettier"
    ],
    "extends": [
        "eslint:recommended",
        "plugin:joyent/style",
        "plugin:joyent/lint",
        "plugin:prettier/recommended"
    ],
```

which includes the "prettier" module in addition to the "joyent" module. Its package.json has them:

```
  "devDependencies": {
    "eslint": "4.13.1",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-joyent": "~2.0.0",
    "eslint-plugin-prettier": "^2.6.0",
    "prettier": "^1.11.1"
  },
```

However for the `check-eslint` target in the eng.git Makefiles we attempted to be clever and avoid having to `npm install` a bunch of other deps just for `make check`. For one, this allowed "dependencies" to have deps that don't install/compile on non-SmartOS, but still allow `make check` to work on non-SmartOS.  Those attempted clever smarts are here: https://github.com/joyent/eng/blob/6fbf2ab73cab336d8a7c4bc56eb74a950e8f6d0c/tools/mk/Makefile.deps#L62-L83

I think, given the ability for eslint config to refer to other plugins and due to this not necessarily being rare going forward (a few repos use prettier, for example), that we perhaps should not rely on these dep-specific smarts being encoded in eng.git Makefiles. Instead each repo can handle the deps required to run `check-eslint`.

Minimally that could be done via this patch (e.g. to triton-mockcloud/Makefile):

```diff
diff --git a/Makefile b/Makefile
index cd6b8b5..5f2e1f8 100644
--- a/Makefile
+++ b/Makefile
@@ -114,6 +114,11 @@ publish: release
 # Includes
 #
 include ./deps/eng/tools/mk/Makefile.deps
+
+$(ESLINT_EXEC): package.json | $(NPM_EXEC)
+	$(NPM) install --only=dev && \
+		touch $(ESLINT_EXEC)
+
 include ./deps/eng/tools/mk/Makefile.node_modules.targ
 ifeq ($(shell uname -s),SunOS)
 	include ./deps/eng/tools/mk/Makefile.node_prebuilt.targ
```


What about changing the eng.git Makefiles to just assume all eslint-required deps are in devDependencies. This mostly allows the same hoped-for benefits of the "don't install all npm deps to run make check".

```diff
diff --git a/tools/mk/Makefile.deps b/tools/mk/Makefile.deps
index 1153809..9f4e571 100644
--- a/tools/mk/Makefile.deps
+++ b/tools/mk/Makefile.deps
@@ -61,24 +61,23 @@ endif
 
 # Install eslint.
 #
-# The install of specific modules is to allow running "make check"
-# without having to do a complete install of all npm dependencies.
+# We assume all eslint-related deps are in "devDependencies" and install
+# only those. This can allow using `make check-eslint` (a) without taking the
+# time to install everything in "dependencies" and (b) even if "dependencies"
+# won't install/build on the current platform.
+#
+# Note that `--only=dev` is silently ignored by the `npm` in node 0.10 and
+# below.
 #
 # NPM_EXEC will be defined if either of "Makefile.{node,node_prebuilt}.defs"
 # is included.
 ifdef NPM
 $(ESLINT_EXEC): package.json | $(NPM_EXEC)
-	ESLINT_VER=$$($(NODE) -e 'console.log(require("./package.json").devDependencies["eslint"] || "")') && \
-	    ESLINT_JOY_VER=$$($(NODE) -e 'console.log(require("./package.json").devDependencies["eslint-plugin-joyent"] || "")') && \
-	    [[ -n $$ESLINT_VER && -n $$ESLINT_JOY_VER ]] && \
-	    $(NPM) install --no-save eslint@$$ESLINT_VER eslint-plugin-joyent@$$ESLINT_JOY_VER && \
+	$(NPM) install --only=dev && \
 	    touch $(ESLINT_EXEC)
 else
 $(ESLINT_EXEC): package.json
-	ESLINT_VER=$$(node -e 'console.log(require("./package.json").devDependencies["eslint"] || "")') && \
-	    ESLINT_JOY_VER=$$(node -e 'console.log(require("./package.json").devDependencies["eslint-plugin-joyent"] || "")') && \
-	    [[ -n $$ESLINT_VER && -n $$ESLINT_JOY_VER ]] && \
-	    npm install --no-save eslint@$$ESLINT_VER eslint-plugin-joyent@$$ESLINT_JOY_VER && \
+	npm install --only=dev && \
 	    touch $(ESLINT_EXEC)
 endif
 
```

**Comment by trentm** [comment]
@timfoster Do you have opinions on my eng.git Makefiles proposal above?

**Comment by timfoster** [comment]
Thanks for the ping. It's a shame that solution would prevents us from doing a fast 'make distclean; make check'.

I wonder could we do something like this instead:

```
timf@jenkins-agent-x86_64-18.4.0 ((HEAD detached at d25b8fc)) git diff
diff --git a/tools/mk/Makefile.deps b/tools/mk/Makefile.deps
index 1153809..330d6fa 100644
--- a/tools/mk/Makefile.deps
+++ b/tools/mk/Makefile.deps
@@ -68,10 +68,11 @@ endif
 # is included.
 ifdef NPM
 $(ESLINT_EXEC): package.json | $(NPM_EXEC)
-       ESLINT_VER=$$($(NODE) -e 'console.log(require("./package.json").devDependencies["eslint"] || "")') && \
-           ESLINT_JOY_VER=$$($(NODE) -e 'console.log(require("./package.json").devDependencies["eslint-plugin-joyent"] || "")') && \
-           [[ -n $$ESLINT_VER && -n $$ESLINT_JOY_VER ]] && \
-           $(NPM) install --no-save eslint@$$ESLINT_VER eslint-plugin-joyent@$$ESLINT_JOY_VER && \
+           ESLINT_DEPS=$$($(NODE) -e 'var p = require("./package.json"); \
+           var d = p.devDependencies; \
+           Object.keys(d).forEach(function(i){ console.log(i+"@"+d[i])});'); \
+           [[ -n $$ESLINT_DEPS ]] && \
+           $(NPM) install --no-save $$ESLINT_DEPS && \
            touch $(ESLINT_EXEC)
 else
 $(ESLINT_EXEC): package.json
timf@jenkins-agent-x86_64-18.4.0 ((HEAD detached at d25b8fc))
```

then, `npm install --no-save $ESLINT_DEPS` will just work, regardless of node version.

Yes, it's not exactly elegant, but maybe it's the hero we deserve?

**Comment by trentm** [comment]
@timfoster FWIW I'm not sure any/many "older node" components are using eslint.

**Comment by trentm** [comment]
Really not that many:

```
$ jr oneach -c 'grep ESLINT_FILES Makefile' 'grep NODE_PREBUILT_VERSION Makefile || true'
# node-bunyan-syslog

# node-asn1

# node-moray-sandbox

# node-fast-messages

# node-artedi

# node-lockfd

# node-macaddr

# triton-prometheus
NODE_PREBUILT_VERSION = v6.17.0

# moray
	NODE_PREBUILT_VERSION	:= v6.17.0

# node-triton-audit-logger

# node-triton-merci-buckets

# node-restify-warden

# node-whyyoulittle

# node-vmadm

# node-triton-netconfig

# node-triton-package-boilerplate

# sdc-fwrule

# sdc-napi
	NODE_PREBUILT_VERSION=v6.17.0

# sdc-net-agent
	NODE_PREBUILT_VERSION =	v4.6.1

# sdc-firewaller-agent
	NODE_PREBUILT_VERSION=v6.17.0

# sdc-fwapi
	NODE_PREBUILT_VERSION=v6.17.0

# sdc-portolan-moray

# sdc-papi
NODE_PREBUILT_VERSION=v6.17.0

# sdc-portolan
	NODE_PREBUILT_VERSION=v6.17.0

# sdc-vm-agent
NODE_PREBUILT_VERSION =	v6.17.0

# triton-cmon-agent
NODE_PREBUILT_VERSION =	v4.9.0

# sdcadm
NODE_PREBUILT_VERSION=v6.17.0

# triton-cmon
NODE_PREBUILT_VERSION=v6.17.0

# triton-grafana
NODE_PREBUILT_VERSION = v6.17.0

# triton-mockcloud
	NODE_PREBUILT_VERSION=v6.17.0

# waferlock
NODE_PREBUILT_VERSION =	v4.9.0
```

**Comment by timfoster** [comment]
> Really not that many:

Ok, in that case, yes, let's do away with that old code in eng.git and use your suggested change to add `--only=dev` assuming that does the right thing.

**Comment by trentm** [comment]
@cburroughs Would you like to add this to this PR:

```
--- a/deps/eng
+++ b/deps/eng
@@ -1 +1 @@
-Subproject commit d25b8fc60fb8c649559924870fe3aaf75e7421d5
+Subproject commit c8690da1d3beedc968c25a931fbf83746b946721
```

?  Else I can, or I can PR that separately.

**Pull request merged**
